version: '3.8'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: aim
    ports:
      - 27017:27017
    networks:
      - backend_network
      - data_network
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    networks:
      - data_network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  frontend:
    build:
      context: ./
      dockerfile: ./frontend/dev.Dockerfile
    command: ["node", "build/dev-server.js"]
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
    init: true

  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    ports:
      - 4444:4444
      - 8888:8888
    networks:
      - backend_network

networks:
  data_network:
  backend_network:
