files: ^backend/
fail_fast: false
default_language_version:
  python: python3.7
repos:
- repo: https://github.com/timothycrosley/isort
  rev: 5.4.2
  hooks:
  - id: isort
    args: [--settings-path=backend/.isort.cfg, backend/]
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
    args: [--config=backend/pyproject.toml, backend/]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.782
  hooks:
  - id: mypy
    language: system
    pass_filenames: false
    args: ['--config-file=backend/mypy.ini', 'backend/']
- repo: https://github.com/PyCQA/flake8
  rev: 3.8.3
  hooks:
  - id: flake8
    args: ['--config=backend/.flake8', 'backend/']
